# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20180923_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='context',
            field=models.TextField(null=True),
        ),
    ]
